ALTER TABLE UTILISATEUR DROP FOREIGN KEY FK_UTILISATEUR_PROFIL_IDPROFIL
ALTER TABLE ADHERENT DROP FOREIGN KEY FK_ADHERENT_CLASSEMENT_IDCLASSEMENT
ALTER TABLE ADHERENT DROP FOREIGN KEY FK_ADHERENT_CLUB_IDCLUB
ALTER TABLE ADHERENT DROP FOREIGN KEY FK_ADHERENT_IDUTILISATEUR
ALTER TABLE ECHEANCIER DROP FOREIGN KEY FK_ECHEANCIER_MATCH_IDMATCH
ALTER TABLE ECHEANCIER DROP FOREIGN KEY FK_ECHEANCIER_TOURNOI_IDTOURNOI
ALTER TABLE EQUIPE DROP FOREIGN KEY FK_EQUIPE_TABLEAUELIMINATION_IDTABLEAUELIMINATION
ALTER TABLE EQUIPE DROP FOREIGN KEY FK_EQUIPE_PARTENAIRE_IDUTILISATEUR
ALTER TABLE EQUIPE DROP FOREIGN KEY FK_EQUIPE_ADHERENT_IDUTILISATEUR
ALTER TABLE EQUIPE DROP FOREIGN KEY FK_EQUIPE_POULE_IDPOULE
ALTER TABLE MATCHS DROP FOREIGN KEY FK_MATCHS_ECHEANCIER_IDECHEANCIER
ALTER TABLE MATCHS DROP FOREIGN KEY FK_MATCHS_TABLEAUELIMINATION_IDTABLEAUELIMINATION
ALTER TABLE MATCHS DROP FOREIGN KEY FK_MATCHS_POULE_IDPOULE
ALTER TABLE MATCHS DROP FOREIGN KEY FK_MATCHS_EQUIPE2_IDEQUIPE
ALTER TABLE MATCHS DROP FOREIGN KEY FK_MATCHS_EQUIPE1_IDEQUIPE
ALTER TABLE POULE DROP FOREIGN KEY FK_POULE_TABLEAU_IDTABLEAU
ALTER TABLE RESULTAT DROP FOREIGN KEY FK_RESULTAT_EQUIPE2_IDEQUIPE
ALTER TABLE RESULTAT DROP FOREIGN KEY FK_RESULTAT_EQUIPE1_IDEQUIPE
ALTER TABLE RESULTAT DROP FOREIGN KEY FK_RESULTAT_MATCH_IDMATCH
ALTER TABLE TABLEAU DROP FOREIGN KEY FK_TABLEAU_TOURNOI_IDTOURNOI
ALTER TABLE TABLEAU DROP FOREIGN KEY TABLEAU_TABLEAUELIMINTATIONS_IDTABLEAUELIMINATION
ALTER TABLE TABLEAUELIMINATION DROP FOREIGN KEY FK_TABLEAUELIMINATION_TABLEAU_IDTABLEAU
ALTER TABLE TABLEAU_ADHERENT DROP FOREIGN KEY FK_TABLEAU_ADHERENT_adherent_IDUTILISATEUR
ALTER TABLE TABLEAU_ADHERENT DROP FOREIGN KEY FK_TABLEAU_ADHERENT_Tableau_IDTABLEAU
DROP TABLE UTILISATEUR
DROP TABLE ADHERENT
DROP TABLE CLASSEMENTFFBA
DROP TABLE CLUB
DROP TABLE PROFIL
DROP TABLE ECHEANCIER
DROP TABLE EQUIPE
DROP TABLE MATCHS
DROP TABLE POULE
DROP TABLE RESULTAT
DROP TABLE TABLEAU
DROP TABLE TABLEAUELIMINATION
DROP TABLE TOURNOI
DROP TABLE TABLEAU_ADHERENT
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
