
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClassementInterop", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClassementInterop {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.ClassementFFBA
     */
    @WebMethod
    @WebResult(name = "classementFFBA", targetNamespace = "")
    @RequestWrapper(localName = "getClassementFfba", targetNamespace = "http://webservice/", className = "webservice.GetClassementFfba")
    @ResponseWrapper(localName = "getClassementFfbaResponse", targetNamespace = "http://webservice/", className = "webservice.GetClassementFfbaResponse")
    @Action(input = "http://webservice/ClassementInterop/getClassementFfbaRequest", output = "http://webservice/ClassementInterop/getClassementFfbaResponse")
    public ClassementFFBA getClassementFfba(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
