
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClassementInteropService", targetNamespace = "http://webservice/", wsdlLocation = "http://201214-10:9090/FFBaClassementWS/ClassementInteropService?wsdl")
public class ClassementInteropService
    extends Service
{

    private final static URL CLASSEMENTINTEROPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLASSEMENTINTEROPSERVICE_EXCEPTION;
    private final static QName CLASSEMENTINTEROPSERVICE_QNAME = new QName("http://webservice/", "ClassementInteropService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201214-10:9090/FFBaClassementWS/ClassementInteropService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSEMENTINTEROPSERVICE_WSDL_LOCATION = url;
        CLASSEMENTINTEROPSERVICE_EXCEPTION = e;
    }

    public ClassementInteropService() {
        super(__getWsdlLocation(), CLASSEMENTINTEROPSERVICE_QNAME);
    }

    public ClassementInteropService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSEMENTINTEROPSERVICE_QNAME, features);
    }

    public ClassementInteropService(URL wsdlLocation) {
        super(wsdlLocation, CLASSEMENTINTEROPSERVICE_QNAME);
    }

    public ClassementInteropService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSEMENTINTEROPSERVICE_QNAME, features);
    }

    public ClassementInteropService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassementInteropService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClassementInterop
     */
    @WebEndpoint(name = "ClassementInteropPort")
    public ClassementInterop getClassementInteropPort() {
        return super.getPort(new QName("http://webservice/", "ClassementInteropPort"), ClassementInterop.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassementInterop
     */
    @WebEndpoint(name = "ClassementInteropPort")
    public ClassementInterop getClassementInteropPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "ClassementInteropPort"), ClassementInterop.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSEMENTINTEROPSERVICE_EXCEPTION!= null) {
            throw CLASSEMENTINTEROPSERVICE_EXCEPTION;
        }
        return CLASSEMENTINTEROPSERVICE_WSDL_LOCATION;
    }

}
